#ARMOR
NETHERITE_HELMET: 3.0
NETHERITE_CHESTPLATE: 8.0
NETHERITE_LEGGINGS: 6.0
NETHERITE_BOOTS: 3.0

#TOOLS
NETHERITE_SWORD: 8.0
DIAMOND_SWORD: 7.0
IRON_SWORD: 6.0
GOLDEN_SWORD: 4.0
STONE_SWORD: 5.0
WOODEN_SWORD: 4.0